# Generated by Django 3.2.13 on 2022-05-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date']},
        ),
    ]
