# Generated by Django 3.2.13 on 2022-05-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0002_alter_announcement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingminute',
            options={'ordering': ['-date']},
        ),
    ]
