# Generated by Django 3.2.13 on 2022-05-28 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0004_userextension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextension',
            options={'permissions': [('add_announcement', 'User can add or clear announcements'), ('add_meeting minute', 'User can add meeting minute'), ('edit_cursus', 'User can edit the Cursus Honorum')]},
        ),
    ]
