# Generated by Django 3.2.13 on 2022-07-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0006_aedile_consul_praetor_quaestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='contents',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='meetingminute',
            name='contents',
            field=models.TextField(max_length=3000),
        ),
    ]
